# Numpy 

NumPy is designed to handle big data swiftly. It includes the following essential components according to the NumPy documentation:

A powerful n-dimensional array object
Sophisticated (broadcasting) functions
Tools for integrating C/C++ and Fortran code
Useful linear algebra, Fourier transform, and random number capabilities

# The Numpy array object

# NumPy Arrays

**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])   ####  List 
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [39]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

406 µs ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [40]:
a = np.arange(1000)
%timeit a**2

1.71 µs ± 231 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [41]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [42]:
#print dimensions

a.ndim

1

In [43]:
#shape

a.shape

(4,)

In [44]:
len(a)

4

In [45]:
# Creating  2-D, 3-D....Array in numpy 

#  [ 0 , 1 , 2
#  3, 4  , 5]

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
b.ndim

2

In [47]:
b.shape

(2, 3)

In [48]:
len(b) #returns the size of the first dimention

2

In [49]:
# Creating a 3 dim array in numpy
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
c.ndim

3

In [51]:
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [52]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [ ]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [ ]:
#Creating a two dimension array with all the valu is one (1)

a = np.ones((3, 3))

a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [53]:
# Creating a two dimension array with all the array with zeros (0)
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:

# Creating the Identity matrix  It is represent by (I3x3)

c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [ ]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
np.diag(a)   #Extract diagonal

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [55]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([0.67270931, 0.26165094, 0.59989432, 0.24309559])

In [56]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 0.70266615, -0.17217638,  2.28855271,  0.03413919])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [57]:
a = np.arange(10)

a.dtype

dtype('int32')

In [ ]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


dtype('float64')

**other datatypes**

In [58]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [59]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [60]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [61]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [63]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])
a
#print(a[2, 2])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [64]:
print(a[2, 2])

3


In [65]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [66]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [68]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [69]:

# For reversing the string using this function

b = np.arange(5)
a = b[::-1] 

a

array([4, 3, 2, 1, 0])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [70]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b = a[::2]   #### Creating a sub array with step size 2
b

array([0, 2, 4, 6, 8])

In [72]:
np.shares_memory(a, b)

True

In [73]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [74]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [75]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [76]:
np.shares_memory(a, c)

False

In [77]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [78]:
a = np.random.randint(0, 20, 15)
a

array([ 9, 19,  9,  0,  6, 12, 19,  7, 10,  5, 16,  0, 14, 18,  0])

In [79]:
mask = (a % 2 == 0)         ### To writien a only even number we can used this operation 

In [80]:
extract_from_a = a[mask]

extract_from_a

array([ 0,  6, 12, 10, 16,  0, 14, 18,  0])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [81]:
a[mask] = -1
a

array([ 9, 19,  9, -1, -1, -1, 19,  7, -1,  5, -1, -1, -1, -1, -1])

**Indexing with an array of integers**

In [82]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Numerical Operation in Numpy

## Elementwise Operations

### 1. Basic Operations

#### with scalars

In [84]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [85]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

#### All arithmetic operates elementwise

In [87]:
b = np.ones(4) + 1

a - b

array([-1.,  0.,  1.,  2.])

In [88]:
a * b

array([2., 4., 6., 8.])

In [9]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


#### comparisions operation

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [90]:
a > b

array([False, False,  True, False])

In [91]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [92]:
np.array_equal(a, c)

True

#### Logical Operations

In [93]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [94]:
np.logical_and(a, b)

array([ True, False, False, False])

In [96]:
a = np.arange(40)

np.sin(a)  

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])

In [97]:
np.log(a)

C:\Users\khana\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165])

In [98]:
np.exp(a)   #evaluates e^x for each element in a given input

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16])

#### Shape Mismatch

In [99]:

#   Can not add two numpy array beacouse of the same size

a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions
###computing sums

In [101]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [102]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [103]:
x.sum(axis=0)   #columns first dimension Axis  = 0 perform column vise operation

array([3, 3])

In [104]:
x.sum(axis=1)  #rows (second dimension)     Axis  = 1 perform column row  operation 

array([2, 4])

# Other reductions

In [105]:
x = np.array([1, 3, 2])
x.min()

1

In [106]:
x.max()

3

In [107]:
x.argmin()# index of minimum element

0

In [108]:
x.argmax()# index of maximum element

1

## Logical Operations

In [109]:
np.all([True, True, False])    ## If any one is False then is writen as false

False

In [110]:
np.any([True, False, False])         ##   If any one is true is writen as True

True

In [111]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

False

In [33]:
np.all(a == a)

True

In [113]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

### Statistics

In [114]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [115]:
y.mean()

3.0

In [116]:
np.median(x)

1.5

In [117]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [118]:
x.std()          # full population standard dev.

0.82915619758885

In [119]:
y.std()

1.9148542155126762